CREATE ROLE db_user;
CREATE ROLE db_manager;
CREATE ROLE db_owner;

GRANT SELECT ON ALL TABLES IN SCHEMA public TO db_user;
--ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT SELECT ON TABLES TO db_user;

GRANT INSERT ON ALL TABLES IN SCHEMA public TO db_manager;
--ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT INSERT ON TABLES TO db_manager;

GRANT INSERT, DELETE, REFERENCES, SELECT, UPDATE, TRIGGER, TRUNCATE ON ALL TABLES IN SCHEMA public TO db_owner;

